### ISSUE TITLE
Configuration string vs. devicetree

### ISSUE THREAD

**Issue by neuschaefer** [sorear/riscv-specs#23]
Andrew Waterman's [mail from 2016-08-19](https://groups.google.com/a/groups.riscv.org/d/msg/sw-dev/XQeRD-yC6A8/UEAUH2m4CwAJ) suggests that devicetree was the kernel configuration mechanism of choice, going forward. Yet, there are many more discussions involving the configuration string, and RISC-V software (bbl, Linux) hasn't switched to devicetrees. Furthermore, the Privileged Architecture Specification 1.9.0 describes the config string.

Which one will be used in Linux?

**Comment by sorear** [comment]
Device tree will almost certainly be used **inside** Linux, because the configuration format needs to be supported per driver, I don't see anyone volunteering to convert every existing devicetree-aware driver, and even if someone did it seems unlikely to be tolerated upstream.

The remaining question for Linux concerns the boot protocol: does the kernel entry point get a flattened devicetree, a textual devicetree, or a config string?  The preponderance of existing code would push for flattened device tree (e.g. QEMU contains logic to generate a device tree and pass it to the kernel); I would prefer this option.

How the device tree is generated in the first place is outside my scope of knowledge.  It'll probably be generated at least in part by the bootloader; M-mode code in general has fewer portability requirements so I'm not in a rush to standardize what goes into ROM.

**Comment by eternaleye** [comment]
Privileged spec 1.9.1 leaves open any-of config string, textual device tree, flattened device tree, and possibly others based on parsing the prefix of the platform config (!). I'm not sure this is a change for the better, and would prefer _exactly one of these_ be blessed.

Given Waterman's previous messages, he's not fond of the binary formats involved in device tree - but that would just seem to militate for passing the textual device tree as the sole format.

In addition, I'd suggest this is _orthogonal_ to the Linux boot protocol, which should definitely take a flattened device tree, in order to not be a special snowflake.

**Comment by sorear** [comment]
Big thread recently on platform configuration which I still owe folks a summary.

**Comment by kasanovic** [comment]
For now, we're punting on this and using DTS for config string syntax.  There's still an unsettled debate on how to handle the other uses for config string, but for now, there are bigger battles.
