### ISSUE TITLE
Claiming the SBI console

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#24]
Having a SBI console device is very nice for a variety of kernel debugging use-cases, but many implementations may not have a dedicated port for the SBI console.  It might, for instance, be a UART which is also accessible to the supervisor and usable for other purposes (at other speeds, etc).  Another example would be a virtualization use case, where high-speed shared memory interfaces like virtio-serial and virtio-console can be used once the supervisor is initialized, but earlyprintk would still benefit from the simplicity of the SBI.

The supervisor and SBI need to coordinate somehow so that, if the supervisor wants to claim the I/O device which happens to be used by the SBI console, it can (a) tell the SBI to stop concurrently accessing the device (b) know itself that it can no longer access SBI console.

**Comment by sam-falvo** [comment]
I propose two functions:

#### int sbi_lock_resource(RCID rcID);

Locks a particular resource.  The resource ID uniquely identifies the resource to lock.  Returns 0 on success; else, an error code.  The concrete type of RCID is TBD.

Some resources are mutually exclusive; e.g., a set of pins that can be configured as a UART _or_ as an Ethernet port might support two resource IDs for RC_UART and RC_ETHERNET; however, if one locks RC_UART, an attempt to lock RC_ETHERNET must necessarily fail.

#### int sbi_unlock_resource(RCID rcID);

Attempts to unlock the specified resource.  Returns 0 if successful, or an error otherwise.  It is an error to unlock an already unlocked resource.

S-mode software is entered with UART pre-locked for its benefit, so that sbi_console_\* functions work as anticipated.  S-mode software is encouraged (but is not required) to unlock the console resource when appropriate.  When unlocked, _or_ when another competing resource that uses the same I/O pins is locked, sbi_console_putchar() performs no operation, while sbi_console_getchar() returns -1.

**Alternatively**

Provide an open/read/write/close protocol, similar to Unix or Plan 9.  Devices are specified with well-known pathnames (perhaps the same path name used to specify a device in the device tree).

**Comment by eternaleye** [comment]
Open questions regarding `RCID`:
- Are values well-known, machine-specific, or is there encoding space for both?
  - The former is more useful for early boot, but the latter may be needed for simple reasons of variable numbers (see: GPIO pins)
- Will a machine ever need more than `2^31 - 1`?
- Will this be something that only works for trivial things and falls over for complex cases (see: mutually-exclusive video connectors _unless_ in clone mode), and thus adds complexity to the supervisor rather than reducing it?
- Unclear in the description: Are we locking a specific _mode_ (RC_ETHERNET), or are we locking a _resource_ (which can take on either ethernet or uart modes of operation) prior to switching its mode?
  - In the former case, this has serious expressiveness concerns (What are we locking to the ethernet mode? Which ethernet device?)
  - In the latter case, this _also_ has serious expressiveness concerns (six pins, possible modes: `(serial | ((SPI | 3xGPIO) (SPI | 3xGPIO))` - no way to express without either very broad locks, nested locks, or combinatorial explosion.
  - In addition, it places harsh restrictions on what can be well-known. If we mandate that rcID 0 must be able to serve the "uart" role, and rcID 1 must be able to serve the "ethernet" role if present, something which offers them both on the same pins cannot offer both well-known IDs.
- This feels like rather a lot of complexity is hiding in this, and it might be better to handle an SBI console in a much less general manner, by providing a simple `log(u8* buf, size_t bytes)` function.
- Logging is pretty much the only sensible device to access in the early-boot environment (before parsing the platform config), and after parsing the platform config the supervisor can bring its full power to bear.
- As a result, _any_ kind of general solution might be overthinking the problem.
- Side benefit of a simple `log` function: Can trivially integrate with `pstore`-like functionality.

**Comment by sorear** [comment]
@eternaleye If we make this a write-only interface, would it be reasonable to say that it may overlap any defined platform device, and once you parse the unspecified-device-data you must stop using log?

**Comment by eternaleye** [comment]
That would make sense to me, yes.

EDIT:  Of course, the platform data could _also_ describe that log interface itself, for instance by saying "yes, this is safe to continue calling, and you can read back its content at `<address>`"

**Comment by sam-falvo** [comment]
The resources discussed in this proposal are abstract resources, so they could refer to multiple concrete resources or they can overlap to a single concrete resource with multiple modes.  All the supervisor knows is that you might have a UART and an Ethernet resource; only the microcontroller knows if the serial port behind them are distinct or not.  So locking a UART might exclude the Ethernet from working and vice versa.  Or not.

Presumably a configuration string would be interpreted by the supervisor to figure this out without having to probe the API.

Regarding complexity, it can't be that complex.  The BIOS used to bootstrap TOS in the Atari ST has vaguely similar functionality, albeit with respect to storage devices and not with stream devices.

**Comment by eternaleye** [comment]
@sam-falvo: My objection is that if it's a generic protocol for resource locking, it's either going to need to handle the real-world cases that are complex, or it's going to be more of a burden to a supervisor than an aid.

Expressing those cases using "abstract resources" that can refer to multiple concrete resources, as you describe, makes it nearly useless for early boot - early boot wants a single thing in a well-known place that it can poke to log things. Increased abstraction and generality runs counter to that.

In addition, _nobody_ has yet managed such a generic protocol for resource locking - the closest anyone has managed is the DRM/KMS Atomic Modesetting API, which is 1.) domain-specific 2.) brand-new 3.) was a royal pain and a half to define in a way that actually worked.

To me, that's a pretty compelling argument that any kind of "hardware mutual exclusion" protocol will be a right bear to design.

**Comment by sam-falvo** [comment]
I don't understand why it would need to handle any cases beyond "turn this feature on and off."  It literally is a feature flag.

If your ethernet driver launches, and your microcontroller overloads your UART with Ethernet functionality, then you want a way to tell sbi_console_putchar to _stop_ what it's doing and just drop characters.  A single bit is sufficient to communicate this.

**Comment by eternaleye** [comment]
And if there are multiple UARTs? If only one is overloaded with ethernet? If another is overloaded with audio? (See also: Android audio jack serial debugging).

The topologies involved can be very nontrivial, and a simple "feature flag" _does not match real hardware_.

A simple rule of "Once you start initializing devices based on the platform config, presume the SBI console is unavailable unless the platform config says otherwise" covers the use cases, with far less new API.

In addition, any such mutual exclusion properties could be specified _declaratively_ in the platform config - allowing the supervisor to decide what to enable/disable up front, rather than via trial-and-error. Note that such behavior being desirable is the entire reason the atomic modesetting API was created: trial-and-error hardware configuration sucks.

**Comment by sam-falvo** [comment]
You typically only have one UART reserved for console I/O during system bring-up.  If you don't, I would put forward the idea that you're doing it wrong.

**Comment by eternaleye** [comment]
I agree - my argument is that in that case, we don't need a general resource locking interface; we just need a relatively simple contract for _when_ handoff happens. Placing that time as "when the supervisor begins initializing devices based on the platform config" opens up a pretty natural flow:

Case 1: Log device is unconditionally safe to continue using
1. Supervisor begins booting, and calls `log()` as needed
2. Supervisor parses platform config, finds that the `riscv,log` node specifies `safe = true`
3. Supervisor continues calling `log()`

Case 2: Log device is not unconditionally safe to continue using
1. Supervisor begins booting, and calls `log()` as needed
2. Supervisor parses platform config, finds that the `riscv,log` node does not specify `safe = true`
3. Supervisor initializes some other logging device
4. Supervisor uses that logging device

Case 2.1: Log device is conditionally safe, and condition is met (optional)
1. Supervisor begins booting, and calls `log()` as needed
2. Supervisor parses platform config, finds that the `riscv,log` node does not specify `safe = true`
3. Supervisor finds that the `riscv,log` node specifies a list of conflicting nodes
4. Supervisor confirms it does not intend to use any of them (and may continue calling `log()` during this)
5. Supervisor continues calling `log()`

Case 2.2: Log device is conditionally safe, and condition is not met (optional)
1. Supervisor begins booting, and calls `log()` as needed
2. Supervisor parses platform config, finds that the `riscv,log` node does not specify `safe = true`
3. Supervisor finds that the `riscv,log` node specifies a list of conflicting nodes
4. Supervisor confirms that it intends to use at least one of them (and may continue calling `log()` during this)
5. Supervisor initializes some other logging device
6. Supervisor uses that logging device

In cases 2.1 and 2.2, as no hardware initialization has yet been done, step (4) can continue calling `log()` - this means that logging is only unavailable for the absolute minimum amount of time (initializing a logging device that conflicts with the SBI logging interface).

This also allows simple systems to only distinguish between cases 1 and 2, reducing the complexity to a single field of a single node.

**Comment by sorear** [comment]
Now part of riscv/riscv-isa-manual#41.
