### ISSUE TITLE
Let's reserve a NOP for cpu_relax now

### ISSUE THREAD

**Issue by sorear** [sorear/riscv-specs#25]
Implementations which have SMT functionality typically want a hinting instruction that reduces the priority of a hart, to use in spinlock loops.  There may be other enabling features for SMT but this is the most impactful one for U-mode.  This could be an existing nop instruction, like `and x0, x0, x0`, or a new PRIV instruction if preferred by the implementers (the latter would have compat impact, but we can get away with that for a little longer).

**Comment by sam-falvo** [comment]
I don't know how many functions under the MISC opcode are assigned, but I think such a feature should be placed there.

Perhaps, another approach: **all** NOPs are inherently relaxed, _except_ for a single NOP defined under MISC.  Rationale: NOPs today tends to be more frequently used as place-holders for code than as instruments to facilitate precise timing for device drivers.  However, the latter category still _occasionally_ pops up; it is here that losing priority amongst other harts would be a bad idea.

**Comment by sorear** [comment]
If it's a placeholder, you want to get over it as quickly as possible.  They're also used quite often for satisfying architectural alignment constraints (e.g. if the machine you're optimizing for has a small direct-mapped branch history table, you don't want two hot branches exactly 1024 bytes apart; aligning branch _targets_ to a small power of two helps on quite a few chips).  A RELAX instruction will stall the current hart for 10+ cycles, while NOPs are usually the fastest thing you can run, discarded in the decode stage.

**Comment by aswaterman** [comment]
The encoding should be as similar as possible to NOP to reduce cost of pattern-matching these hints.  FENCE -, - only differs by one bit from addi x0, x0, 0, but still probably isn't the best choice, because some simple microarchitectures ignore the FENCE arguments and always execute a full fence.

We'd also like the most common HINTs to be encodable in the RVC encoding space reserved for HINTs.  This suggests addi x0, x0, N, a.k.a., C.LI x0, N.  We can clarify the user ISA to state these instructions are HINTs in the base ISA, not just RVC.

**Comment by sorear** [comment]
Refiled riscv/riscv-isa-manual#43
